site_name: Mihir Patel — EGR314 Individual Datasheet
site_url: https://mihir-patel-64.github.io
repo_url: https://github.com/Mihir-Patel-64/Mihir-Patel-64.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  logo: static/logo314.svg
  favicon: static/logo314.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static
  
copyright: "Copyright &copy; 2026 Mihir Patel — Team 302 EGR314"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mihir-Patel-64
      name: Mihir Patel on GitHub